env:
  es6: true
  browser: true
  commonjs: true

extends: [
  "plugin:import/react",
  "plugin:react-hooks/recommended",
  "eslint:recommended",
  "plugin:@typescript-eslint/recommended",
]

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 8
  sourceType: module

plugins: [
  "react",
  "react-hooks",
  "@typescript-eslint",
]

rules: {
  "react-hooks/rules-of-hooks": "error",
  "react-hooks/exhaustive-deps": ["warn", {
    "additionalHooks": "(useMyCustomHook|useMyOtherCustomHook)"
  }],
  "no-loss-of-precision": "off",
  "@typescript-eslint/no-loss-of-precision": ["error"],
}

settings:
  react:
    version: "16"
  import/resolver:
    node:
      extensions: [".js", ".jsx"]
