env:
  es6: true
  browser: true
  commonjs: true
  jest: true

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 8
  sourceType: module

plugins: [
  "react",
  "react-hooks",
  "@typescript-eslint",
  # "prettier",
]

extends: [
  "eslint:recommended",
  "plugin:react/recommended",
  "plugin:react-hooks/recommended",
  "plugin:import/react",
  "plugin:@typescript-eslint/recommended",
  # "prettier",
  # "plugin:prettier/recommended",
]

settings:
  react:
    version: "16"
  import/resolver:
    node:
      extensions: [".js", ".jsx"]

overrides: [
  {
    files: ["*.config.js"],
    rules: {
      "@typescript-eslint/no-var-requires": "off",
      "no-undef": "off",
    },
  }
]

rules: {
  "no-console": "error",
  "react/react-in-jsx-scope": "off",
  "react-hooks/rules-of-hooks": "error",
  "react-hooks/exhaustive-deps": ["warn", {
    "additionalHooks": "(useMyCustomHook|useMyOtherCustomHook)"
  }],
  "no-loss-of-precision": "off",
  "@typescript-eslint/no-loss-of-precision": ["error"],
  # "react/jsx-first-prop-new-line": [2, "multiline-multiprop"],
  # "react/jsx-max-props-per-line": [2, { "maximum": 3, "when": "always" }],
  "brace-style": ["error", "1tbs", { "allowSingleLine": true }],
  "indent": ["error", 2],
  "one-var-declaration-per-line": ["error", "always"],
  "no-multiple-empty-lines": ["error", {
    "max": 2,
    "maxEOF": 0,
    "maxBOF": 0,
  }],
  "padding-line-between-statements": ["error",
    { blankLine: "always", prev: "directive", next: "*" },
    { blankLine: "any", prev: "directive", next: "directive" },
    { blankLine: "always", prev: "*", next: "export" },
    { blankLine: "any", prev: "export", next: "export" },
    { blankLine: "always", prev: "import", next: "*" },
    { blankLine: "any", prev: "import", next: "import" },
  ],
  "no-trailing-spaces": "error",
  "key-spacing": ["error", {
    "beforeColon": false,
    "afterColon": true,
    "mode": "strict",
  }],
  "function-call-argument-newline": ["error", "consistent"],
  "comma-dangle": ["error", {
    "arrays": "always-multiline",
    "objects": "always-multiline",
    "imports": "always-multiline",
    "exports": "always",
    "functions": "only-multiline"
  }],
  "object-curly-newline": ["error", {
    # "ObjectExpression": { "multiline": true, "minProperties": 1 },
    # "ObjectPattern": "always", #{ "multiline": true },
    "ImportDeclaration": { "multiline": true, "minProperties": 5 },
    "ExportDeclaration": "always",
  }],
  "object-property-newline": ["error", { "allowAllPropertiesOnSameLine": true }],
  # "prettier/prettier": "error",
}
